# This is a basic workflow to help you get started with Actions

name: Generate Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: # This configuration does not affect the page_build event above
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Generate Docs
        uses: sersoft-gmbh/swifty-docs-action@v1.2.1
        with:
          # The path to the output folder.
          output: docs # optional
