name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13
    strategy:
      matrix:
        swift: ["5.5"]
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 15
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
