name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
          matrix:
            swift: ["5.5"]
    runs-on: macos-latest
    steps:
    - uses: fwal/setup-swift@v1.11.0
      with:
          swift-version: ${{ matrix.swift }}
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
